### PR TITLE
TAR-195 renaming to webapp-view

### PR DESCRIPTION
**Pull request by lukehansell-hx**
#### What does this PR do?
Renames the project output form app-modules to webapp-views.

After some discussion we've settled on webapp as the name of the clientside project Refactor is currently building. This generator creates React views as standalone projects. Therefore we're renaming it to generator-webapp-views, since this isn't in production it shouldn't cause any issues!

Also, after this PR is merged the repo should be renamed to generator-webapp-view.

#### What unit or integration tests does this PR have?
Refactored current tests to new naming convention.

#### What selenium tests does this PR have?
none

#### How should a developer review this? 
review the code to make sure I've not missed any instances of "app-module" and run the tests using `npm test`.

#### How should this be manually tested?
- rename the directory you checked the project out into to 'generator-webapp-view'. (We have to do this because of how Yeoman autoloads generators)
- npm link this project. (in project directory `npm link`)
- make sure you have `yo` installed on your mac globally by running `npm install -g yo`
- create a new directory on your mac and cd into it `mkdir test && cd test/`
- run `yo webapp-view`
- run `npm run build-dev`
- now run `open dev/index.html`

Your default browser should now open with a blank window. If you inspect the body element you should see in the `<body>` tag a `<div>` with the class name of `webapp-view-[whatever you named the project]`.

#### Any background context you want to provide?
[Yo](yeoman.io) is a standard tool for generating boilerplate and template code.
This generator creates a default [React](http://facebook.github.io/react/) view for inclusion within out WebApp project.
The WebApp project is designed to modularise the HX site and improve the speed at which new features and white labels can be developed.

The structure of the views (as explained in the readme) has been defined so that each shared view can be used in any project for which these views are intended and also so that non-shared views in apps can be shared in the future more easily.

For this project we're creating a webapp which allows the inclusion of these external features which will be installed via npm. The views created by this generator will be one such artefact to be npm installed. By doing this we can have two or more apps using the same view which can be versioned and updated more easily in each. For instance, if your view is a product tile, you may wish to include this in more than one project and in more than one place in each.

Hopefully this little explanation has cleared some questions, but more than likely it's made more. Feel free to ask any questions on anything you're unsure of for this PR.

#### What are the relevant tickets?
[TAR-195](https://holidayextras.jira.com/browse/TAR-195)

#### What gif best describes how you feel about this work?

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by HeinBehrenshx** [comment]
I will take IP/dev review

**Comment by HeinBehrenshx** [comment]
+1, but I cannot tick the boxes (they are greyed out).

**Comment by HeinBehrenshx** [comment]
+1

**Comment by hxjamesmcneil** [comment]
Taking SE/Dev

**Comment by hxjamesmcneil** [comment]
:+1:

**Comment by michaelcarter** [comment]
+1 Guru/SE

**Pull request merged**
